name: publish

on:
  workflow_dispatch:

jobs:
  push:
    name: push package on pypi
    runs-on: ubuntu-22.04
    environment:
      name: pypi
      url: https://pypi.org/project/ytdlmusid/   
    permissions:
      id-token: write      
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'    
      - name: update pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
      #installation          
      - name: install pyweatherfr
        run: |
          pip install .
      #test
      - name: Launch test
        run: |
          pyweatherfr nantes
          echo 1 | pyweatherfr nantes -w
          pyweatherfr tokyo -w
          pyweatherfr nouméa -n -v
          pyweatherfr 38700 -j2 --nocache
          pyweatherfr grenoble -p50 --utc -c
          pyweatherfr Ancenis-Saint-Géréon -p3 --pc --nocolor
          pyweatherfr barcelone -n --nocolor -w
          echo 2 | pyweatherfr barcelona -w
          echo 3 | pyweatherfr "london" --lang -w
          echo 3 | pyweatherfr "springfield, USA" -w
          echo 10 | pyweatherfr "beaulieu, France"
          echo 10 | pyweatherfr "beaulieu, France"| grep "\[11\]" || echo ok
          echo 5 | pyweatherfr "springfield, Jamaique" -w
          echo 5 | pyweatherfr "springfield, Jamaique" -w | grep "\[6\]" || echo ok
          pyweatherfr -v
          (pyweatherfr ancenis || echo ok) | grep aucune
          (pyweatherfr tokyo || echo ok) | grep aucune
          (pyweatherfr tokyo || echo ok) | grep "Relancez la avec -w"
      - name: install pep517
        run: |
          pip install pep517
      - name: build
        run: python3 -m pep517.build --source --binary --out-dir dist/ .
      - name: publish to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
         

