name: publish

on:
  workflow_dispatch:

jobs:
  push:
    name: push package on pypi
    runs-on: ubuntu-22.04
    environment:
      name: pypi
      url: https://pypi.org/project/ytdlmusid/   
    permissions:
      id-token: write      
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'    
      - name: update pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
      #installation          
      - name: install pyweatherfr
        run: |
          pip install .
      #test
      - name: Launch test
        run: |
          pyweatherfr nantes
          pyweatherfr nouméa -n -v
          pyweatherfr 38700 -j2 --nocache
          pyweatherfr grenoble -p50 --utc -c
          pyweatherfr ancenis -p3 --pc --nocolor
          pyweatherfr barcelone -n --nocolor
          echo 2 | pyweatherfr barcelona
      - name: install pep517
        run: |
          pip install pep517
      - name: build
        run: python3 -m pep517.build --source --binary --out-dir dist/ .
      - name: publish to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
         

