name: auto twitter

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  twitter:       
    runs-on: 'ubuntu-20.04'
    name: publish daily weather for nantes in twitter
    steps:
      #preparation
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: x64
      - uses: actions/setup-node@v2
        with:
          node-version: '14'                                      
      - name : install carbon-now-cli
        run: npm i -g carbon-now-cli
      - name: update pip
        run: |
          python -m pip install --upgrade pip
      #installation          
      - name: install pyweatherfr 
        run: |
          pip install pyweatherfr && pyweatherfr nantes && mkdir export
      - name: execute
        run: pyweatherfr nantes -j 0 > export/export.txt
      #5 tests (unstable)    
      - name: export_png_1
        id: export_png_1 
        timeout-minutes: 3
        continue-on-error: true
        run: carbon-now -h -t export export/export.txt
      - name: export_png_2
        id: export_png_2
        timeout-minutes: 3
        if: steps.export_png_1.outcome=='failure'
        continue-on-error: true
        run: carbon-now -h -t export export/export.txt 
      - name: export_png_3
        id: export_png_3
        timeout-minutes: 3
        if: steps.export_png_2.outcome=='failure'
        continue-on-error: true
        run: carbon-now -h -t export export/export.txt 
      - name: export_png_4
        id: export_png_4
        timeout-minutes: 3
        if: steps.export_png_3.outcome=='failure'
        continue-on-error: true
        run: carbon-now -h -t export export/export.txt 
      - name: export_png_5
        id: export_png_5
        timeout-minutes: 3
        if: steps.export_png_4.outcome=='failure'
        continue-on-error: true 
        run: carbon-now -h -t export export/export.txt
      - name: set the status              # set the workflow status if command failed
        if: always()
        run: |
          if ${{ steps.export_png_1.outcome=='success' || steps.export_png_2.outcome=='success' || steps.export_png_3.outcome=='success' || steps.export_png_4.outcome=='success' || steps.export_png_5.outcome=='success' }}; then
             echo fine
          else
             exit 1
          fi   
      #- name: tweet
      #  env: 
      #    CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      #    CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
      #    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #    ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      #  run: pip install twython && python .github/daily_tweet.py  
    
