name: auto twitter

on:
  workflow_dispatch:

jobs:
  twitter:       
    runs-on: 'ubuntu-20.04'
    name: test package with ubuntu20.04 et python3.9
    steps:
      #preparation
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: x64                            
      - name: update pip
        run: |
          python -m pip install --upgrade pip
      #installation          
      - name: install pypodo
        run: |
          pip install .
      #test
      - name: Launch one
        run: mkdir export && mkdir snaps && pyweatherfr nantes
      - name: Launch two
        run: pyweatherfr nantes > export/export.txt
      - name: Generate pngs
        uses: sharadcodes/code-snap-action@v1.0
        with:
          source_folder: "export" # This field is required and it is the folder which contains the source files.
          output_folder: "snaps" # This field is required and it is the folder which contains the snaps.
          syntax_theme: "emacs" # This field is required and it is the syntax highlighting theme that will be used.        
      - name: list
        run: ls snaps/*
    
