name: auto twitter

on:
  workflow_dispatch:

jobs:
  twitter:       
    runs-on: 'ubuntu-20.04'
    name: publish daily weather for nantes in twitter
    steps:
      #preparation
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: x64
      - uses: actions/setup-node@v2
        with:
          node-version: '14'                                      
      - name : install carbon-now-cli
        run: npm i -g carbon-now-cli
      - name: update pip
        run: |
          python -m pip install --upgrade pip
      #installation          
      - name: install pyweatherfr 
        run: |
          pip install pyweatherfr && pyweatherfr nantes && mkdir export
      - name: execute
        run: pyweatherfr nantes > export/export.txt
      - name: export png
        run: carbon-now -h -t export.png export/export.txt  
      - name: list
        run: ls export/*
      - name: tweet
        env: 
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: pip install twython && python .github/tweet.py  
    
